### ISSUE TITLE
Implement querying for metadata

### ISSUE THREAD

**Issue by future-is-present** [GerardoGa/BigchianDB-android#1]
First of all, such an amazing job you did @GerardoGa 

I am not able to use the metadata endpoint provided by BigchainDB with this driver. It would be nice to implement it. Here is explained in the JS driver: https://docs.bigchaindb.com/projects/js-driver/en/latest/usage.html#querying-for-metadata

**Comment by GerardoGa** [comment]
done :)
```
       JsonArray jsonArray = MetadataApi.searchMetadata(searchKey);
       Log.d("JSON ARRAY", jsonArray.toString());
```

**Comment by future-is-present** [comment]
Ohh was fast!!
Maybe you are not used to work with Github. But usually you open a new PR that closes the issue. Anyways I am very happy with what you are doing :) I'll close the issue then
